language: node_js
git:
  submodules: false
cache:
  yarn: true
  npm: true
  directories:
    - node_modules
before_install:
  - npm i -g npm@6.12.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
stages:
  - name: lint
  - name: tests
    install: true
  - name: release
    install: true
    if: branch = master AND NOT tag AND type NOT IN (pull_request)
jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: release
      script: yarn release
matrix:
  fast_finish: true
