language: node_js
git:
  submodules: false
cache:
  yarn: true
  npm: true
  directories:
    - node_modules
before_install:
  - npm i -g npm@6.9.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn
jobs:
  include:
    - stage: lint
      script: yarn eslint '*.js'
    - stage: release
      install: true
      before_script: yarn global add semantic-release semantic-release-gitmoji @semantic-release/github @semantic-release/npm
      script: npx semantic-release
      if: branch = master AND NOT tag
matrix:
  fast_finish: true
